## name:     Ivory Ink Light
## author:   Denis Panfilov
## license:  MIT
## blurb:    High-contrast near-white light theme ported from Ivory Ink for Zed

# The basic colors
foreground              #040807
background              #F5F5F5
selection_foreground    #040807
selection_background    #90C4FF

# Cursor colors
cursor                  #040807
cursor_text_color       #FFFFFF

# Scrollbar colors
scrollbar_handle_color  #8A928C
scrollbar_track_color   #ECEFEB

# URL color when hovering with mouse
url_color               #002E78

# Kitty window border colors
active_border_color     #004EAE
inactive_border_color   #6E766F
bell_border_color       #4F3000

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #040807
active_tab_background   #F2F4F1
inactive_tab_foreground #404942
inactive_tab_background #F5F5F5
tab_bar_background      #ECEFEB

# Colors for marks (marked text in the terminal)
mark1_foreground #FFFFFF
mark1_background #004B27
mark2_foreground #FFFFFF
mark2_background #8A0014
mark3_foreground #FFFFFF
mark3_background #002E78

# The 16 terminal colors

# black
color0  #050A08
color8  #2C3832

# red
color1  #8A0014
color9  #B00020

# green
color2  #004B27
color10 #006B37

# yellow
color3  #4F3000
color11 #6E4600

# blue
color4  #002E78
color12 #004EAE

# magenta
color5  #4C126F
color13 #6A219A

# cyan
color6  #004B55
color14 #006B78

# white
color7  #26312B
color15 #050A08
