## name:     Ivory Ink Dark
## author:   Denis Panfilov
## license:  MIT
## blurb:    Soft low-contrast dark theme ported from Ivory Ink for Zed

# The basic colors
foreground              #EEE7DA
background              #151719
selection_foreground    #FFFFFF
selection_background    #334B5F

# Cursor colors
cursor                  #FFFFFF
cursor_text_color       #151719

# Scrollbar colors
scrollbar_handle_color  #2D3130
scrollbar_track_color   #131516

# URL color when hovering with mouse
url_color               #FFD166

# Kitty window border colors
active_border_color     #8CC8FF
inactive_border_color   #4D5658
bell_border_color       #FFD166

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #FFFFFF
active_tab_background   #1C1F20
inactive_tab_foreground #B7B5AA
inactive_tab_background #151719
tab_bar_background      #161819

# Colors for marks (marked text in the terminal)
mark1_foreground #151719
mark1_background #7EE787
mark2_foreground #151719
mark2_background #FF7B72
mark3_foreground #151719
mark3_background #79C0FF

# The 16 terminal colors

# black
color0  #5C6664
color8  #9AA5A1

# red
color1  #FF7B72
color9  #FF9B9B

# green
color2  #7EE787
color10 #A5F3A1

# yellow
color3  #FFD166
color11 #FFE08A

# blue
color4  #79C0FF
color12 #A5D6FF

# magenta
color5  #D2A8FF
color13 #E2C5FF

# cyan
color6  #56D4DD
color14 #8BEAF2

# white
color7  #E6DED1
color15 #FFF7EA
