## name:     Ivory Ink Dark
## author:   Denis Panfilov
## license:  MIT
## blurb:    Soft low-contrast dark theme ported from Ivory Ink for Zed

# The basic colors
foreground              #D6D0C4
background              #151719
selection_foreground    #151719
selection_background    #282723

# Cursor colors
cursor                  #D6D0C4
cursor_text_color       #151719

# Scrollbar colors
scrollbar_handle_color  #2D3130
scrollbar_track_color   #131516

# URL color when hovering with mouse
url_color               #C8B889

# Kitty window border colors
active_border_color     #8F8A82
inactive_border_color   #3A3A36
bell_border_color       #AA9162

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #D0CAC0
active_tab_background   #1C1F20
inactive_tab_foreground #858A84
inactive_tab_background #151719
tab_bar_background      #161819

# Colors for marks (marked text in the terminal)
mark1_foreground #151719
mark1_background #84B88A
mark2_foreground #151719
mark2_background #D48B93
mark3_foreground #151719
mark3_background #6FA4D8

# The 16 terminal colors

# black
color0  #4E5352
color8  #737973

# red
color1  #D48B93
color9  #E7A6AC

# green
color2  #84B88A
color10 #A3D09F

# yellow
color3  #C9A85F
color11 #E1C277

# blue
color4  #6FA4D8
color12 #8DBBE8

# magenta
color5  #B98AC0
color13 #D1A4D8

# cyan
color6  #65B9C5
color14 #83D4DE

# white
color7  #D2CCC1
color15 #E8E0D2
