## name:     Ivory Ink Light
## author:   Denis Panfilov
## license:  MIT
## blurb:    Near-white minimal light theme ported from Ivory Ink for Zed

# The basic colors
foreground              #0B0F0C
background              #FFFFFF
selection_foreground    #0B0F0C
selection_background    #C9D8E8

# Cursor colors
cursor                  #0B0F0C
cursor_text_color       #FFFFFF

# Scrollbar colors
scrollbar_handle_color  #DDDDD9
scrollbar_track_color   #F8F8F5

# URL color when hovering with mouse
url_color               #003F8C

# Kitty window border colors
active_border_color     #6D6B64
inactive_border_color   #B8B7B1
bell_border_color       #7A5A00

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0B0F0C
active_tab_background   #FFFFFF
inactive_tab_foreground #202620
inactive_tab_background #F7F7F4
tab_bar_background      #F8F8F5

# Colors for marks (marked text in the terminal)
mark1_foreground #FFFFFF
mark1_background #006B35
mark2_foreground #FFFFFF
mark2_background #A00024
mark3_foreground #FFFFFF
mark3_background #005EA8

# The 16 terminal colors

# black
color0  #202621
color8  #5D6762

# red
color1  #A00024
color9  #C01635

# green
color2  #006B35
color10 #008A45

# yellow
color3  #6E5000
color11 #8A6500

# blue
color4  #005EA8
color12 #0078D4

# magenta
color5  #6D238A
color13 #8A35A8

# cyan
color6  #006D7A
color14 #008A9A

# white
color7  #5A605B
color15 #202620
