## name:     Ivory Ink Dark
## author:   Denis Panfilov
## license:  MIT
## blurb:    Soft low-contrast dark theme ported from Ivory Ink for Zed

# The basic colors
foreground              #EEE7DA
background              #151719
selection_foreground    #FFFFFF
selection_background    #46443D

# Cursor colors
cursor                  #FFFFFF
cursor_text_color       #151719

# Scrollbar colors
scrollbar_handle_color  #2D3130
scrollbar_track_color   #131516

# URL color when hovering with mouse
url_color               #E5C07B

# Kitty window border colors
active_border_color     #B6A98E
inactive_border_color   #4D4D47
bell_border_color       #E5C07B

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #FFFFFF
active_tab_background   #1C1F20
inactive_tab_foreground #B7B5AA
inactive_tab_background #151719
tab_bar_background      #161819

# Colors for marks (marked text in the terminal)
mark1_foreground #151719
mark1_background #98C379
mark2_foreground #151719
mark2_background #E06C75
mark3_foreground #151719
mark3_background #61AFEF

# The 16 terminal colors

# black
color0  #56605D
color8  #8B9692

# red
color1  #EF7D88
color9  #FF9BA3

# green
color2  #9FCD7A
color10 #BDEB94

# yellow
color3  #EBCB7A
color11 #FFE08A

# blue
color4  #74B9FF
color12 #9ED0FF

# magenta
color5  #D28BEE
color13 #E7B0FF

# cyan
color6  #5FD4DE
color14 #8BEAF2

# white
color7  #E0D8CC
color15 #FFF7EA
