## name:     Ivory Ink Dark
## author:   Denis Panfilov
## license:  MIT
## blurb:    Soft low-contrast dark theme ported from Ivory Ink for Zed

# The basic colors
foreground              #D6D0C4
background              #151719
selection_foreground    #151719
selection_background    #282723

# Cursor colors
cursor                  #D6D0C4
cursor_text_color       #151719

# Scrollbar colors
scrollbar_handle_color  #2D3130
scrollbar_track_color   #131516

# URL color when hovering with mouse
url_color               #C8B889

# Kitty window border colors
active_border_color     #8F8A82
inactive_border_color   #3A3A36
bell_border_color       #AA9162

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #D0CAC0
active_tab_background   #1C1F20
inactive_tab_foreground #858A84
inactive_tab_background #151719
tab_bar_background      #161819

# Colors for marks (marked text in the terminal)
mark1_foreground #151719
mark1_background #81847E
mark2_foreground #151719
mark2_background #B98F90
mark3_foreground #151719
mark3_background #8499AC

# The 16 terminal colors

# black
color0  #4E5352
color8  #737973

# red
color1  #BD8C91
color9  #D0A1A2

# green
color2  #819C8F
color10 #99B3A6

# yellow
color3  #AA9162
color11 #C5AE7A

# blue
color4  #7E95A4
color12 #93A9B8

# magenta
color5  #9E879D
color13 #B8A1B5

# cyan
color6  #789B99
color14 #89A9A7

# white
color7  #D2CCC1
color15 #E8E0D2
